version: "3.9"
services:
  nginx:
    ports:
      - "5000:80"
      # - "80:80"
      # - "443:443"
    volumes:
      - ./server/config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  app:
    build:
      args:
        NODE_ENV: development
    volumes:
      - ./server:/app
      - /app/node_modules
      - ./client:/app/client:ro
    # volumes:
    #   - ./server/:/server
    #   - /server/node_modules

      # - ./config/nodemon.json:/app/nodemon.json
    environment:
      - NODE_ENV=development
      - MONGO_USER=Bader
      - MONGO_PASSWORD=myPassword
      - MONGO_DB_NAME=myBlog
      - SESSION_SECRET=someSecret
      - REDIS_USER=default
      - REDIS_PASSWORD=myPassword
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=articles
      - JWT_SECRET=jwtSecret
      - JWT_LIFETIME=3h
      - SENDGRID_API_KEY=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
      - MAIL_USER=www.bader.com9@gmail.com
      - MAIL_PASS=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
      #  👾 what's awesome about sendGrid, is that because i forgot to ignore this file, they deleted the api👾
    command: npm start
    # command: sh -c "npm --prefix ./client run build && npm start"

  # client:
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile
  #     args:
  #       NODE_ENV: development
  #   environment:
  #     - PORT=8080
  #   volumes:
  #     - ./client/:/client
  #     - /client/node_modules

  #   command: sh -c "npm run build"
    # command: npm run build
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=Bader
      - MONGO_INITDB_ROOT_PASSWORD=myPassword
  redis:
    environment:
      - REDIS_USER=default
      - REDIS_PASSWORD=myPassword
  #   command:
  #     - redis-server --requirepass myPassword