version: "3.9"
services:
  nginx:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx/encrypted.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www/:/var/www/certbot/:ro
  certbot:  # Official build of EFF's Certbot tool for obtaining TLS/SSL certificates from Let's Encrypt.
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
  bun:
    deploy:
      replicas: 8
      restart_policy:
        condition: any
      update_config:
        parallelism: 2
        delay: 15s
    build:
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
      - MONGO_USER=Bader
      - MONGO_PASSWORD=myPassword
      - SESSION_SECRET=someSecret
      - REDIS_USER=Bader
      - REDIS_PASSWORD=myPassword
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=articles
    command: npm start
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=Bader
      - MONGO_INITDB_ROOT_PASSWORD=myPassword